baseURL = "https://blog.wallaroolabs.com"
languageCode = "en-us"
title = "Wallaroo Labs Engineering Blog"
theme = "sendence-hugo-steam-theme"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 5

[permalinks]
  post = "/:year/:month/:slug/"

[params]
	title = "Wallaroo Labs Engineering Blog"
	subtitle = "\"I wanna go fast\""
	copyright = ""

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []
  logo      = "img/logo_horiz.png"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Wallaroo Labs"
	bio = ""
	description = "Official blog of the Wallaroo Labs Engineering team"
  orghome = "https://www.wallaroolabs.com/"

	# Link your social networks (optional)
	location = ""
	twitter = "wallaroolabs"
	linkedin = "WallarooLabs"
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "WallarooLabs"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
	useSummaryIfNoDescription = true

  # Splash segment prompt and button label
  splashprompt = "Wallaroo 0.5.3 has been released with a ton of improvements!"
  splashurl = "https://github.com/WallarooLabs/wallaroo/releases/tag/0.5.3"
  splashbutton = "Learn more"

[menu]

  [[menu.main]]
    name = "Home"
    # pre = "<i class='fa fa-road'></i>"
    url = "http://www.wallaroolabs.com/"
    weight = -100

  [[menu.main]]
    name = "Technology"
    # pre = "<i class='fa fa-road'></i>"
    url = "http://www.wallaroolabs.com/technology/"
    weight = -90


  [[menu.main]]
    name = "Developers"
    # pre = "<i class='fa fa-road'></i>"
    url = "http://www.wallaroolabs.com/developers/"
    weight = -70

    [[menu.main]]
      name = "Blog"
      # pre = "<i class='fa fa-road'></i>"
      url = "/"
      weight = -50

  [[menu.main]]
    name = "" # Save for later, if client wants to implement search
    pre = "<i class='fa fa-github' style='margin-left:5px;'></i>"
    url = "https://github.com/wallaroolabs/wallaroo"
    weight = -30
