baseurl = "https://blog.wallaroolabs.com"
languageCode = "en-us"
title = "Wallaroo Labs Engineering"
theme = "sendence-hugo-steam-theme"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 5

[permalinks]
  post = "/:year/:month/:title/"

[params]
	title = "Wallaroo Labs"
	subtitle = "\"I wanna go fast\""
	copyright = ""

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	fontbody = 'Archivo Narrow'
	fontheading = 'Archivo Narrow'
	fontlogo = 'Raleway'

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Wallaroo Labs"
	bio = ""
	description = "Official blog of the Wallaroo Labs Engineering team"

	# Link your social networks (optional)
	location = ""
	twitter = "wallaroolabs"
	linkedin = "sendence"
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "WallarooLabs"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
	useSummaryIfNoDescription = true
